<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="CSS/PooEstilos.css">
    <title>PROGRAMACION Orientada a Objetos</title>
</head>
<body>
    
    <header>
        <br>
        <h5>Vanessa Alexandra Mendoza Arias ADSI </h5>
        <br>
    </header>


     <section>
    <div>
        <h1><center>PROGRAMACION ORIENTADAS A OBJETOS</center></h1>
    </div>

   
        <p class="reseña">
            La orientacion a Objetos es el paradigma de programacion mas utilizado actualmente.
            Es dificil programar en un lenguaje que no permita en mayor o menor medida la orientacion a objetos.
            
        </p>

        <br>

        <p>
            La orientacion Progrmada a Objetos (POO) es un paradigma de programacion totalmente diferente al metodo clasico
            de progrmacion, el cual utiliza objetos y su comportamiento para resolver problemas y generar programas y aplicaciones
            informaticas.
            <br><br>
            Con progrmacion Orientada a Objetos (POO) se aumenta la modularidad de los programas y la reutilizacion de 
            de los mismo.  Se diferencia de la programacion clasica porque utiliza tecnicas nuevas como el polimorfismo
            
            <br><br>
            <p class="reseña">polimorfismo: es la capacidad que tienen ciertos lenguajes para hacer que, al enviar el mismo mensaje (o, en otras 
                palabras, invocar al mismo método) desde distintos objetos, cada uno de esos objetos pueda 
                responder a ese mensaje (o a esa invocación) de forma distinta.
            </p>

        </p>
        <br><br>

        <h2><center>ANALISIS, DISEÑO, Y PROGRMACION ORIENTADA A OBJETOS</center></h2>

        <P>
            Todos los progrmas se reducen a objetos que tienen una serie de atributos y asociados, un comportamiento
            o procedimiento llamados "metodos". Estos Objetos son instanciados en clases interaccionaran unos con otros 
            y de esa manera se diseñaran aplicaciones y progrmas.
            <br><br>
            
            Hoy en dia es dificil programar sin utilizar programacion orientada a objetos(POO). Esta forma de programar es
            mas cercana al modo en que expresariamos las cosas en la vida real que la que se da a otros tipos de programacion
            clasicos. Los analistas y programadores deben pensar las cosas de una manera distinta para plasmar dichos conceptos
            en progrmacion en terminos de objetos, atributos y metodos.
        </P>

        <img src="IMG/Imagen1.png" alt="">


        <a href="ClaseyObjeto.php">Siguiente</a>
        <br><br>

    </section>
    
    
</body>
</html>